project:
  type: website
  output-dir: docs

website:
  title: "Think Tank UU"
  navbar:
    left:
      - href: index.qmd
        text: June 5
  repo-url: https://github.com/gerkovink/think
  repo-actions: [edit, issue]

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

